# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a538b4a3c418f713899c6821f8b1a41b2450082d73ee706407033b50f3802c6e64ded5e0245e7d9326cb0e734f611c8f8612fe9d09dc3a1fe8ae09098e48c0af

test:
  secret_key_base: e44234ac034a8fe83dfb2dd407c37b0c8e38505a81d59b39656e66ff252938bf1cecbacf0707914043d1cb2693942b3be2e77e8755b04c599df10a8561f46dda

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
